version: '3.5'

services:
  api:
    build:
      context: ./heal-api
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: api
        WORKING_DIR: /usr/api/
    expose:
      - 4000
    ports:
      - 4000:4000
    environment:
      REDIS_URL: redis://redis:6379/0
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
    env_file:
      - ./heal-api/.env
    volumes:
      - ./heal-api:/usr/api
    depends_on:
      - postgres
      - redis
    command: [ "npm run", "dev" ]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: frontend
        WORKING_DIR: /usr/ui/
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENV=development
      - BACKEND=api:4000
      - NODE_PATH=/usr/ui/
    env_file:
      - ./heal-client/.env
    volumes:
      - ./heal-client:/usr/ui
    depends_on:
      - api
    command: [ "npm", "", "start" ]

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s0me-p4sswd
      - POSTGRES_DB=HealDB
      - POSTGRES_PORT=5432
    restart: always
    env_file: ./DB.env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
