FROM node:14.15.4-alpine3.12

ARG PACKAGE_PATH=./
ARG WORKING_DIR=/usr/api

WORKDIR ${WORKING_DIR}

COPY ${PACKAGE_PATH}/package*.json ${WORKING_DIR}

RUN npm install

COPY ${PACKAGE_PATH} ${WORKING_DIR}

VOLUME $WORKING_DIR/node_modules

CMD [ "npm run", "watch" , "start:dev" ]

